#!/usr/bin/env bash

#: Title       : c-bootstrap
#: Date        : 25-07-2017
#: Author      : "Ahmed Khaled" <nemoload@aol.com>
#: Version     : 1.0
#: Description : Create a dummy *.c file with The Standard
#                I/O library inclueded and the main function
#: Options     : [1] Takes an optional *.c file name. If it was empty
#                the file would be named main.c (default)

FILE_NAME=${1:-"main.c"} 
cat<<EOF > $FILE_NAME
#include <stdio.h>

int main(int argc, char *argv[])
{
  char * msg = "Bootstrapped!";
  printf("%s\n",msg);

  return 0;
}
EOF
