#!/usr/bin/env bash

set -e

mkdir manga
cd manga
curl -s $1 |\
    sed 's/,/\n/g'  |\
    perl -ne '/(system\/releases\/\d{3}\/\d{3}\/\d{3}\/(\d{3}|\d{3}-\d{3})\.(jpg|png))/ && print "https://dynasty-scans.com/$1\n"' |\
    xargs -I {} wget -nv -nc {}
cd ..
zip -r manga.cbz manga
rm -r manga
