#!/usr/bin/env bash

#: Title       : github_get_raw
#: Date        : 09-07-2018
#: Author      : "Ahmed Khaled" <nemoload@aol.com>
#: Version     : 1.0
#: Description : Given a Github file url it prints its content
#: Options     : [1] A GitHub URL

echo "$1" |\
    sed 's#https://github\.com#https://raw\.githubusercontent\.com#' |\
    sed 's#/blob/#/#' |\
    xargs curl -sL
