#!/bin/env ruby

#: Title       : swagtext
#: Date        : 25-07-2017
#: Author      : "Ahmed Khaled" <nemoload@aol.com>
#: Version     : 1.0
#: Description : takes a "text" as an argument and
#                returns a "tExT".
#: Options     : [1] The text to be swag'ed.

text = ARGV.join(' ')
ignore = true
res = ''
text.downcase.each_char do |c|
  res.concat(ignore ? c : c.capitalize)
  ignore = !ignore
end

print res, "\n"
